// GENERATED BY HAND (no build_runner)
part of 'aircraft.dart';
class AircraftAdapter extends TypeAdapter<Aircraft> {
  @override final int typeId = 0;
  @override Aircraft read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{};
    for (int i = 0; i < numOfFields; i++) { fields[reader.readByte()] = reader.read(); }
    return Aircraft(id: fields[0] as String, registration: fields[1] as String, name: fields[2] as String, mtowKg: fields[3] as double, correctionFactors: fields[5] as CorrectionFactors, grassPenaltyPercentIfNoGrassData: fields[4] as double?, points: (fields[6] as List).cast<PerformancePoint>(),);
  }
  @override void write(BinaryWriter writer, Aircraft obj) {
    writer..writeByte(7)..writeByte(0)..write(obj.id)..writeByte(1)..write(obj.registration)..writeByte(2)..write(obj.name)..writeByte(3)..write(obj.mtowKg)..writeByte(4)..write(obj.grassPenaltyPercentIfNoGrassData)..writeByte(5)..write(obj.correctionFactors)..writeByte(6)..write(obj.points);
  }
}