// GENERATED BY HAND (no build_runner)
part of 'correction_factors.dart';
class CorrectionFactorsAdapter extends TypeAdapter<CorrectionFactors> {
  @override final int typeId = 2;
  @override CorrectionFactors read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{};
    for (int i = 0; i < numOfFields; i++) { fields[reader.readByte()] = reader.read(); }
    return CorrectionFactors(headwindTakeoffPercentPerKt: fields[0] as double, tailwindTakeoffPercentPerKt: fields[1] as double, headwindLandingPercentPerKt: fields[2] as double, tailwindLandingPercentPerKt: fields[3] as double, slopeTakeoffPercentPerPercent: fields[4] as double, slopeLandingPercentPerPercent: fields[5] as double);
  }
  @override void write(BinaryWriter writer, CorrectionFactors obj) {
    writer..writeByte(6)..writeByte(0)..write(obj.headwindTakeoffPercentPerKt)..writeByte(1)..write(obj.tailwindTakeoffPercentPerKt)..writeByte(2)..write(obj.headwindLandingPercentPerKt)..writeByte(3)..write(obj.tailwindLandingPercentPerKt)..writeByte(4)..write(obj.slopeTakeoffPercentPerPercent)..writeByte(5)..write(obj.slopeLandingPercentPerPercent);
  }
}