// GENERATED BY HAND (no build_runner)
part of 'performance_point.dart';
class PerformancePointAdapter extends TypeAdapter<PerformancePoint> {
  @override final int typeId = 1;
  @override PerformancePoint read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{};
    for (int i = 0; i < numOfFields; i++) { fields[reader.readByte()] = reader.read(); }
    return PerformancePoint(runwayType: fields[0] as String, weightKg: fields[1] as double, pressureAltitudeFt: fields[2] as double, deltaIsaC: fields[3] as double, takeoffGroundRollM: fields[4] as double, takeoffOver50M: fields[5] as double, landingGroundRollM: fields[6] as double, landingOver50M: fields[7] as double);
  }
  @override void write(BinaryWriter writer, PerformancePoint obj) {
    writer..writeByte(8)..writeByte(0)..write(obj.runwayType)..writeByte(1)..write(obj.weightKg)..writeByte(2)..write(obj.pressureAltitudeFt)..writeByte(3)..write(obj.deltaIsaC)..writeByte(4)..write(obj.takeoffGroundRollM)..writeByte(5)..write(obj.takeoffOver50M)..writeByte(6)..write(obj.landingGroundRollM)..writeByte(7)..write(obj.landingOver50M);
  }
}