// GENERATED BY HAND (no build_runner)
part of 'performance_point.dart';
class PerformancePointAdapter extends TypeAdapter<PerformancePoint> {
  @override final int typeId = 1;
  @override PerformancePoint read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{};
    for (int i = 0; i < numOfFields; i++) { fields[reader.readByte()] = reader.read(); }
    return PerformancePoint(
      runwayType: fields[0] as String,
      weightKg: fields[1] as double,
      pressureAltitudeFt: fields[2] as double,
      deltaIsaC: fields[3] as double,
      takeoffGroundRollM: fields[4] as double,
      takeoffOver50M: fields[5] as double,
      landingGroundRollM: fields[6] as double,
      landingOver50M: fields[7] as double,
      headwindTakeoffPercentPerKt: fields[8] as double?,
      tailwindTakeoffPercentPerKt: fields[9] as double?,
      headwindLandingPercentPerKt: fields[10] as double?,
      tailwindLandingPercentPerKt: fields[11] as double?,
      slopeTakeoffPercentPerPercent: fields[12] as double?,
      slopeLandingPercentPerPercent: fields[13] as double?,
    );
  }
  @override void write(BinaryWriter writer, PerformancePoint obj) {
    final hasCorrections = obj.headwindTakeoffPercentPerKt != null ||
        obj.tailwindTakeoffPercentPerKt != null ||
        obj.headwindLandingPercentPerKt != null ||
        obj.tailwindLandingPercentPerKt != null ||
        obj.slopeTakeoffPercentPerPercent != null ||
        obj.slopeLandingPercentPerPercent != null;
    writer.writeByte(hasCorrections ? 14 : 8);
    writer..writeByte(0)..write(obj.runwayType)..writeByte(1)..write(obj.weightKg)..writeByte(2)..write(obj.pressureAltitudeFt)..writeByte(3)..write(obj.deltaIsaC)..writeByte(4)..write(obj.takeoffGroundRollM)..writeByte(5)..write(obj.takeoffOver50M)..writeByte(6)..write(obj.landingGroundRollM)..writeByte(7)..write(obj.landingOver50M);
    if (hasCorrections) {
      writer..writeByte(8)..write(obj.headwindTakeoffPercentPerKt)..writeByte(9)..write(obj.tailwindTakeoffPercentPerKt)..writeByte(10)..write(obj.headwindLandingPercentPerKt)..writeByte(11)..write(obj.tailwindLandingPercentPerKt)..writeByte(12)..write(obj.slopeTakeoffPercentPerPercent)..writeByte(13)..write(obj.slopeLandingPercentPerPercent);
    }
  }
}
